name: ach_bot

services:
  bot:
    build: .
    container_name: ach_bot
    restart: unless-stopped
    env_file:
      - /home/marshall/ash_bot/.env
    secrets:
      - bot_credentials
    volumes:
      - /home/marshall/ash_bot/user_bot.db:/ach_bot/user_bot.db
      - /home/marshall/ash_bot/token.json:/ach_bot/token.json
    networks:
      - nawah
      
secrets:
  bot_credentials:
    file: /home/marshall/ash_bot/credentials.json

networks:
  nawah:
    external: true 
       
